    <w:lvl w:ilvl="0">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%1."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="720"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="1">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%2."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="1440"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="2">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%3."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="2160"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="3">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%4."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="2880"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="4">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%5."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="3600"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="5">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%6."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="4320"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="6">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%7."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="5040"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="7">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%8."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="5760"/>
      </w:pPr>
    </w:lvl>
    <w:lvl w:ilvl="8">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%9."/>
      <w:lvlJc w:val="left"/>
      <w:pPr>
        <w:ind w:hanging="360" w:left="6480"/>
      </w:pPr>
    </w:lvl>
